import { systemSounds } from '../../utils/sounds';

// 1. Single Source of Truth for all Dungeon Data
export const DUNGEON_LIST = {
  // Standard Gates (Ranked)
  'E-Rank': { time: 300, exp: 50, gold: 200, type: 'Standard', rank: 'E', color: 'blue' },
  'D-Rank': { time: 600, exp: 150, gold: 600, type: 'Standard', rank: 'D', color: 'blue' },
  'C-Rank': { time: 1200, exp: 400, gold: 1500, type: 'Standard', rank: 'C', color: 'blue' },
  'B-Rank': { time: 2400, exp: 1000, gold: 4000, type: 'Standard', rank: 'B', color: 'blue' },
  'A-Rank': { time: 3600, exp: 2500, gold: 10000, type: 'Standard', rank: 'A', color: 'blue' },
  'S-Rank': { time: 7200, exp: 10000, gold: 50000, type: 'Standard', rank: 'S', color: 'blue' },

  // Specialized Dungeons
  'Instant': { 
    time: 60, exp: 100, gold: 500, type: 'System', rank: 'E', color: 'purple',
    lore: 'A dungeon generated by the System for rapid growth.' 
  },
  'Red': { 
    time: 1500, exp: 5000, gold: 20000, type: 'Hazard', rank: 'B', color: 'red',
    lore: 'A gate that connects to another world.' 
  },
  'Double': { 
    time: 3000, exp: 15000, gold: 0, type: 'Hidden', rank: 'S', color: 'red',
    lore: 'High risk, absolute reward.' 
  },
  'Job Change': { 
    time: 1800, exp: 8000, gold: 5000, type: 'Trial', rank: 'A', color: 'orange',
    lore: 'A test to determine the players true class.' 
  },
  'Demon Castle': { 
    time: 5400, exp: 20000, gold: 100000, type: 'Tower', rank: 'S', color: 'orange',
    lore: 'A 100-floor tower filled with demon souls.' 
  }
};

export const createQuestSlice = (set, get) => ({
  bossActive: false,
  bossHealth: 100,
  bossMaxHealth: 100,
  inDungeon: false,
  dungeonTimer: 0,
  activeDungeon: null,
  penaltyActive: false,

  quests: [
    { id: 1, title: "Pushups [0/50]", completed: false, reward: 25, goldReward: 100, isHard: false },
    { id: 2, title: "Sit-ups [0/50]", completed: false, reward: 25, goldReward: 100, isHard: false },
    { id: 3, title: "Squats [0/50]", completed: false, reward: 25, goldReward: 100, isHard: false },
    { id: 4, title: "Walking [6K]", completed: false, reward: 50, goldReward: 250, isHard: true },
  ],

  achievements: [
    { id: 'a1', title: 'First Blood', desc: 'Clear 1 Dungeon', target: 1, completed: false, reward: { gold: 500 } },
    { id: 'a2', title: 'Iron Will', desc: 'Reach 20 Strength', target: 20, stat: 'strength', completed: false, reward: { points: 2 } },
  ],

  resetQuests: () => set((state) => ({
    quests: state.quests.map(q => ({ ...q, completed: false })),
    hasReportedMorning: false,
    waterGlassCount: 0
  })),

  completeQuest: (id) => {
    const state = get();
    const quest = state.quests.find(q => q.id === id);
    if (quest && !quest.completed) {
      systemSounds.questComplete();
      
      if (state.addExperience) state.addExperience(quest.reward);
      else if (state.gainExp) state.gainExp(quest.reward);

      const updatedQuests = state.quests.map(q => q.id === id ? { ...q, completed: true } : q);
      
      set({ 
        gold: state.gold + quest.goldReward, 
        quests: updatedQuests, 
        fatigue: Math.min(state.fatigue + 10, 100),
        // FIXED: Only trigger "Arise" if it's a Hard quest (like the 6K Walk)
        extractionAvailable: quest.isHard ? true : false 
      });
    }
  },

  enterDungeon: (type) => {
    const data = DUNGEON_LIST[type];
    if (data) {
      set({ inDungeon: true, dungeonTimer: data.time, activeDungeon: data });
    }
  },

  completeDungeon: () => {
    const state = get();
    systemSounds.questComplete();
    if (state.addExperience) state.addExperience(state.activeDungeon?.exp || 100);
    else if (state.gainExp) state.gainExp(state.activeDungeon?.exp || 100);

    set({ 
      inDungeon: false, 
      activeDungeon: null, 
      extractionAvailable: true // Dungeons ALWAYS allow extraction
    });
  },

  attackBoss: () => set((state) => {
    systemSounds.click();
    const damage = state.stats.strength + (state.shadows.length * 5);
    const newHealth = Math.max(0, state.bossHealth - damage);
    if (newHealth === 0) {
      const ranks = ["E", "D", "C", "B", "A", "S"];
      set({ 
        bossActive: false, 
        rank: ranks[ranks.indexOf(state.rank) + 1] || "S", 
        gold: state.gold + 5000,
        extractionAvailable: true // Bosses ALWAYS allow extraction
      });
    }
    return { bossHealth: newHealth };
  }),
});